name: Build FolderMate

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Instalare Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Instalare dependinte
        run: |
          pip install customtkinter
          pip install pyinstaller
      
      - name: Compilare exe
        run: |
          pyinstaller --onedir --windowed --name "FolderMate" --hidden-import customtkinter main.py
      
      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: FolderMate-Windows
          path: dist/FolderMate/
